### PR TITLE
Feature/new constructor

### PR DESCRIPTION
**Pull request by tlubitz**

### CODE REVIEW

**Comment by tlubitz** [comment]
Hi @eladnoor

I changed the constructor of SBtabTable and SBtabDocument. The new construction of objects is documented in the README of SBtab/python/

But basically it now works rather like this:

sbtab = SBtab.SBtabTable()
sbtab.set_filename('filename')
sbtab.add_sbtab_string(sbtab_string)

...so that no initial parameters are required anymore and empty objects can be built.

Please be aware that I *only* changed this in the commandline version to be found in SBtab/python/SBtab.py, and *not* in the pip installer or the online interface or whatnot, yet.

It would be cool if you could have a look at your panda function SBtabTable.fromDataFrame(), whether you can simplify that one now. I know you were struggling with all the mandatory parameters. And feedback is welcome on the overall move (sorry, I wanted to assign you as reviewer for the pull request, but forgot; would you be willing to act as reviewer in the future? There are going to be a bunch of PRs soon in this repo).

Best
Timo

**Comment by eladnoor** [comment]
Hi @timolubitz ,

This is a very welcome change, I'll be happy to test it (probably only next week, though) and maybe rewrite the fromDataFrame() function.
And also being a reviewer for future PRs is a great idea. 

Best,
Elad

**Comment by tlubitz** [comment]
Cool, then I'll maybe send some PRs into your direction next week.

Cheers
Timo


Am Do., 16. Juli 2020 um 11:44 Uhr schrieb Elad Noor <
notifications@github.com>:

**Comment by eladnoor** [comment]
Hi,

I rewrote the from_data_frame() function, and also tested it with my code, so far it seems to work.
I pushed the changes to the [branch](https://github.com/tlubitz/SBtab/tree/feature/new_constructor) so I think you can just merge it again if you think this is good enough.

**Comment by tlubitz** [comment]
Thanks, Elad,

I merged this into the master!

Best
Timo


Am Di., 21. Juli 2020 um 11:52 Uhr schrieb Elad Noor <
notifications@github.com>:

**Pull request merged**
