### PR TITLE
Fix: if SBtab Table is added to SBtabDocument, do not rely on it havi…

### PR DESCRIPTION
**Pull request by tlubitz**
…ng a filename

### CODE REVIEW

**Comment by eladnoor** [comment]
Wouldn't it be safer to set .filename to None if it is not provided explicitly?

**Comment by tlubitz** [comment]
You mean in the SBtabTable class, right?

**Comment by eladnoor** [comment]
Yes, for the SBtabDocument this is already the case:
https://github.com/tlubitz/SBtab/blob/00c63099f86493bd9fb204f7727e3690add2217a/python/SBtab.py#L956

**Comment by tlubitz** [comment]
Okay, I changed this. Have a look, please

**Pull request merged**
